### ISSUE TITLE
No way to check which click is being used to open Mystery crates

### ISSUE THREAD

**Issue by puigru** [Hazebyte/CrateReloadedAPI#15]
Useful in case we want to check which click is being used to open a mystery crate.

**Comment by imWillX** [comment]
I faced some issues implementing this specifically the way I did it. I'm using listener that is listening to CrateInteractEvent to handle the OPEN/PREVIEW of crates. This allows users with a certain priority to cancel the event. (This is probably what i'm doing wrong, but continue reading for details)

Lets say that plugin A listens for CrateInteractEvent...

Scenario 1: If it's priority is lower than my listener, it will be able to cancel my event, but the CrateAction won't be updated yet because my CrateInteractEvent fires after due to higher priority.

Scenario 2: If it's priority is higher than my listener, it will not be able to cancel the event. The CrateAction will be updated since my listener fires before Plugin A's. 

Perhaps i'm doing this wrong. Let me think about it, and if you have suggestions, that'd be welcomed.

**Comment by puigru** [comment]
@imWillX Oh, I understand what you're saying, I don't think it's a wrong way to go about it, what I had I mind was firing an event for both CrateAction.RIGHT_CLICK and CrateAction.PREVIEW regardless of if it goes through or not. However, maybe the best solution may be to keep it like it is, and simply implement a CrateInteractEvent#getRootAction(), that returns the Action of the PlayerInteractEvent.

**Comment by imWillX** [comment]
I'll try the simple implementation :)
